<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <script src="https://kit.fontawesome.com/4514d9060c.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{{ asset('front/css/style.css') }}"/>
    <link rel="shortcut icon" href="{{ asset('front/img/favicon.png') }}" />
    <title>CORE RESOURCES | PRIVACY POLICY</title>
</head>
<body>
    @include('Pagina.components.menu-ancla')
    <div class="container py-5">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-1"></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-10">
                <div class="text-center">
                    <h1 class="mExtraBold txt-azul">Privacy Notice</h1>
                </div>
                <div class="gRegular">
                    <p>
                        This document is composed by the Privacy Notice for the purposes of the provisions of the Federal Law for the Protection of Personal Data in Possession of Private Parties (the "LFPDP") and the provisions that emanate from it or are related to it. This Privacy Notice (referred to as "Notice") applies to the personal information collected about the Data Subject by CINCO NOVENTA Y TRES CONSULTORES SA DE CV, in it´s capacity as Data Controller. The purpose of this Notice is to protect your personal data, through it´s legitimate, controlled and informed treatment, in order to guarantee your privacy, as well as your right to informational self-determination.
                    </p>
                    <p>
                        According to article 3, section V, of the Law, Personal Data is understood as: Any information concerning an identified or identifiable natural person according to  the provisions of section I of article 16 of the Law, will be the Responsible for your personal information (Personal Data).
                    </p>
                    <h6 class="mBold txt-azul">What information do we collect?</h6> 
                    <p>
                        The Responsible collects information that can reasonably identify you, for example, but not limited to: your first and last name; date of birth; e-mail address, general information of your profile.
                    </p>
                    <h6 class="mBold txt-azul">How do we use or share the information we collect?</h6> 
                    <p>
                        By sending via email your personal information to the different representatives of <b class="mBold txt-azul">CINCO NOVENTA Y TRES CONSULTORES SA DE CV.</b> and/or completing the online application form that appears on the page, you accept and authorize <b class="mBold txt-azul">CINCO NOVENTA Y TRES CONSULTORES SA DE CV.</b> to use and treat in an automated way your personal data and information provided, which will be part of our database with the purpose of using them in an enunciative, but not limited way to: identify you, communicate with you, contact you, send you information, update our database, and promote all the artistic content generated by <b class="mBold txt-azul">CINCO NOVENTA Y TRES CONSULTORES SA DE CV.</b>.
                    </p>
                    <p>
                        <b class="mBold txt-azul">CINCO NOVENTA Y TRES CONSULTORES SA DE CV.</b> as responsible for the treatment of your personal data, is obliged to comply with the principles of legality, consent, information, quality, purpose, loyalty, proportionality and responsibility protected by the Law; therefore, based on articles 13 and 14 of the Law, <b class="mBold txt-azul">CINCO NOVENTA Y TRES CONSULTORES SA DE CV.</b> is committed to keep your personal data strictly confidential, as well as to maintain the administrative, technical and physical security measures to protect them against any damage, loss, alteration, access or unauthorized treatment. How to contact our Personal Data Department?
                        For any communication about our Privacy Notice, please contact our Personal Data Department: d.murguia@toilconsulting.com
                    </p> 
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-1"></div>
        </div>
    </div>
    @include('Pagina.components.footer-ancla')
</body>
</html>